env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

service:
- docker

addons:
  apt:
    update: true
    packages:
    - libappindicator1
    - fonts-liberation
    - bash
    - curl
    - libxml2-utils
    - docker-ce
    - google-chrome-stable

install: true
before_install:
- nvm install lts/*
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
- sudo add-apt-repository universe -y
- sudo apt-get update -yqq
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends tree jq python-pip
- sudo pip install docker-compose httpie >/dev/null 2>&1

script:
- export root=$(pwd)
#
- ./gradlew >/dev/null
- npm start
- sleep 15
#
- npm run ls
- npm run show
#
- cat ~/.pm2/logs/pm2-java-spring-boot-out.log
- npm run kill

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
